RECRUIT_FOLDER_DIR  F:\\Recruitment_data\\applicant
RECRUIT_FOLDER advertisement_pdf, degree, photo, signature, certificate
ADMIN_FOLDER_DIR  F:\\Recruitment_data\\admin
LOGO_DIR images//logo.png
EMAIL_SENDER erecruit_admin@nrsc.gov.in
EMAIL_HOST 172.19.1.201
SMS_URL http://192.168.0.199:8080/sms1/smssendnew.jsp?
INTERNAL_USE NO
OTP_DURATION 10
LOGFILE F:\\Logs

############################################ 
# Database Connection Properties for Postgres
############################################ 
drivers org.postgresql.Driver

#recruit.url jdbc:postgresql://127.0.0.1:5432/erecruit
recruit.url jdbc:postgresql://172.19.2.60:5432/erecruit
#recruit.url jdbc:postgresql://172.19.2.29:5432/erecruit
recruit.user nrsc
recruit.password tiger
recruit.maxconn 0 